//@version=4
study(shorttitle="BB", title="Bollinger Bands", overlay=true)
length = input(20, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50)
basis = sma(src, length)
dev = mult * stdev(src, length)

p0 = plot(basis, color=color.white, title = "basis")

sell0 = basis + dev * 0.75
buy0 = basis - dev * 0.75
p1 = plot(sell0, color=color.green, title ="sell0")
p2 = plot(buy0, color=color.red, title = "buy0")


sell1 = basis + dev * 0.38
buy1 = basis - dev * 0.38
p3 = plot(sell1, color=color.green, title ="sell0")
p4 = plot(buy1, color=color.red, title = "buy0")

fill(p1, p0)
fill(p2, p0, color=color.red)